name: live_easy
description: "Interview mechin test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  pin_code_fields: ^8.0.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  intl: ^0.18.0
  country_picker: ^2.0.26
  flutterotpfield: ^0.0.3
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_core_platform_interface: ^5.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
